#Use norminette command when necessary
alias norminette="~/.norminette/norminette.rb"

#Use code . in terminal to open vscode with current directory
code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
